version: '3.8'

services:
  flask-service:
    # docker file kahan hai
    build:
      context: ./flask
    # container ka naam
    container_name: flask-app
    # kaunse port se app chalega
    expose:
      - "80"
    # local code ko container ke code se mount kare jisse sirf up karne se updated code run karega
    volumes:
      - ./flask:/app
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
